### ISSUE TITLE
Display multiple frames in an Image

### ISSUE THREAD

**Issue by Braisly** [cylab-tw/bluelight#29]
Hi @cylien and @birdeggb2777 , we are trying to figure out if we are able to see multiple frames of an image with Bluelight but this moment we only can see the first frame. Is that correct?

I saw that there was this development to support multiframe images:
https://github.com/cylab-tw/bluelight/issues/10

I understand that right now you can open a multiframe image but you are not able to visualize the other frames.

Thank you.

**Comment by birdeggb2777** [comment]
Oh, I forgot to assign the branch of the Github Page to the master branch, but I have fixed it now. Could you please try again?

**Comment by Braisly** [comment]
Hi @birdeggb2777 , could you add these changes to BLPlugin that we see the branch does not contain the changes?

Let me know if you need help.

Thank you!

**Comment by cylien** [comment]
This PR has been merged into the master, you can switch to the master.

**Comment by Braisly** [comment]
> This PR has been merged into the master, you can switch to the master.

How do you change between frames? We tried in master and it always remains the same frame.

**Comment by cylien** [comment]
I tested it and it works fine. 

![media(1)](https://user-images.githubusercontent.com/3929275/232640289-bfcc99eb-64b9-4f77-9d41-084236fee9a4.gif)

**Comment by Braisly** [comment]
It looks that some images are working correctly but other not.

For example this image:
https://file.io/ydtJ5iJ7vzUc

If you are not able to download it, let me know. You can view the image on any DICOM Viewer.

**Comment by cylien** [comment]
The bug has been fixed. 
85cdeb5

**Comment by Braisly** [comment]
Hi @cylien and @birdeggb2777,

We saw that the issue related with the previous images is solved but not all multiframe images could be opened correctly with BlueLight.

Look at this example: https://www.dropbox.com/s/k7obz27f07z1kmk/XA-MONO2-8-12x-catheter.gz?dl=0

Let me know how we can proceed to fix this issue.

Thank you so much.

**Comment by cylien** [comment]
@Braisly fixed it. 

8ffbb14

**Comment by Braisly** [comment]
Thank you @cylien but there is another DICOM image that is still failing. We are looking for an example to share with you (as we can not have the permission to upload it on the Internet).

**Comment by Braisly** [comment]
This is the file that Bluelight is not able to process @cylien 

[162CB78B.zip](https://github.com/cylab-tw/bluelight/files/11382492/162CB78B.zip)

Thank you so much!

**Comment by birdeggb2777** [comment]
@Braisly fixed it.
It had some problems decoding JPEG Baseline (Transfer Syntax UID: 1.2.840.10008.1.2.4.50).

**Comment by cylien** [comment]
BTW, this IOD is a whole slide image, you can use another project: [mainecoon](https://github.com/cylab-tw/mainecoon) to display it.

We are still writing a new architecture now. The source code on GitHub is still the older version, and it still works fine. I just uploaded the test image to Raccoon and fixed it.

here is the display result:  https://cylab-tw.github.io/mainecoon/bluelight-WSI/html/index.html?StudyInstanceUID=1.2.826.0.1.3244452.3.2.1876091050

**Comment by Braisly** [comment]
Thank you @cylien and @birdeggb2777 but with the current changes the BlueLight does not show any major improvement. Now we are able to load the image but we do not view it correctly. At the same time we are not able to change between frames.

Moreover if we upload a heavier images than the previous, we are not able to load them.

The Mainecoon looks a great viewer but we need to tag images from different sources and we believe that BlueLight is a suitable tool for this task. 

How can we help you to process Pathology images on Bluelight? To see the different frames and load these kind of images properly.

Let us know if you need any help, we appreciate your big effort @cylien and @birdeggb2777 .

**Comment by cylien** [comment]
> with the current changes the BlueLight does not show any major improvement. Now we are able to load the image but we do not view it correctly. 

We are trying to fix it in BlueLight ASAP.  However, this type of image is not proper for displaying in BlueLight.
 
> How can we help you to process Pathology images on Bluelight? To see the different frames and load these kind of images properly.

Some features e.g. tag, XNAT, in BlueLight may be added in Mainecoon that I will discuss with developers in a future version. Perhaps you can use BlueLight to tag the image and view WSI in Mainecoon.

**Comment by cylien** [comment]
@Braisly this bug had been fixed. 
b93a407

**Comment by Braisly** [comment]
@cylien It looks that now is working properly for images with small size. 

Nevertheless for an image of 155.000 KB Bluelight is not able to load it correctly (major size 155 MB). But this is another problem.

**Comment by cylien** [comment]
> Nevertheless for an image of 155.000 KB Bluelight is not able to load it correctly (major size 155 MB). But this is another problem.

DICOM WG-26 recommends viewer can query and retrieve the WSI from a DICOMweb server for displaying partial frames to avoid downloading whole images which are huge in size. (in your case). The design of BlueLight is for general medical images mostly radiography so we also developed another DICOM viewer, especially for dealing with WSI.

Even though BlueLight cannot display huge sizes of WSI, I have tested that BlueLight has a limitation is about up to 100MB for displaying all frames in WSI, the tag function is still operable.

**Comment by Braisly** [comment]
Hmmmm but with a minor step with BlueLight you will be able to open any image. Probably with one viewer is more useful for the user.

What are the restrictions for the BlueLight as a universal viewer? What are your thoughts?

**Comment by cylien** [comment]
BlueLight supports the display for most of the DICOM  SOP class of the DICOM objects, such as radiographic images, annotations, video, and SR which is similar to the other commercial or open-source/open software DICOM viewers. 

Recently, the tools for the DCOM WSI have been increasing rapidly in recent years. However, the WSI is not an entirely new SOP class in DIOCM, this standard has been released over 10 years. I think that is because of the new communication protocol in DICOM i.e., DICOMweb facilitates the development of the digital pathology e.g., some WSI tools such as [OpenSlide](https://openslide.org/), [Orthanc Plugin for WSI](https://book.orthanc-server.com/plugins/wsi.html), [Slim](https://github.com/ImagingDataCommons/slim), [Google WSI Viewer](https://github.com/GoogleCloudPlatform/dicomweb-wsi-viewer), etc., were created.

We had tried to integrate the display of WSI in native BlueLight, however,  it didn't reach the target effect that we expected. Because the behavior in operating digital pathology is totally different than general medical image. 

For example, WSI required a mini-map to display the global location when the user navigating the pathology image which is not necessary for general medical images. The other example is for navigating images, WSI is required to cascade all frames to construct a map, and zoom to switch ratios of slide images. That operational behavior conflicts with the general medical image.

In addition, the software architecture of BlueLight will be refactored if BlueLight is compatible with these two types of images that BlueLight will become "fatter" and "over-engineering". So we designed an independent WSI Viewer differing from BlueLight which is similar to the other project such as Orthanc, and Slim. 

The following demonstration shows the prototype of the BlueLight plugin for WSI connected to a DICOMweb server one year ago.
![ezgif-4-79cde9ff46](https://github.com/cylab-tw/bluelight/assets/3929275/2ef24789-950f-407f-97d1-f2a55fee89de)

**Comment by Terabuck** [comment]
Hi! Working on a Tomosynthesis image, the WW/WL values applied to an image are not preserved when scrolling to the adjacent images, requiring continuos WW/WL adjustments.

**Comment by cylien** [comment]
Add this feature and merge it into the master.
